FROM anatolelucet/neovim:0.10.0-ubuntu

WORKDIR /usr/src

# Install curl
RUN apt-get update && apt-get install -y curl git socat ttyd

RUN sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

COPY . .

RUN nvim -u init.vim +'PlugInstall --sync' +qa

RUN chmod +x /usr/src/run_socat.sh

ENTRYPOINT ["/usr/src/run_socat.sh"]
